const ATTRIBUTE_STATUS = "status";
const ATTRIBUTE_TITLE = "title";
const ATTRIBUTE_NUMBER = "number";
const ATTRIBUTE_HTML_URL = "html_url";
const ATTRIBUTE_OWNER_ID = "owner_id";

module.exports = Object.freeze({
    ATTRIBUTE_STATUS: ATTRIBUTE_STATUS,
    ATTRIBUTE_TITLE: ATTRIBUTE_TITLE,
    ATTRIBUTE_NUMBER: ATTRIBUTE_NUMBER,
    ATTRIBUTE_HTML_URL: ATTRIBUTE_HTML_URL,
    ATTRIBUTE_OWNER_ID: ATTRIBUTE_OWNER_ID,
});
