const ATTRIBUTE_BITBUCKET_ID = "bitbucket_id";
const ATTRIBUTE_CHAT_ID = "chat_id";
const ATTRIBUTE_NAME = "name";

module.exports = Object.freeze({
    ATTRIBUTE_BITBUCKET_ID: ATTRIBUTE_BITBUCKET_ID,
    ATTRIBUTE_CHAT_ID: ATTRIBUTE_CHAT_ID,
    ATTRIBUTE_NAME: ATTRIBUTE_NAME,
});
