name: Pull Request Build

on:
    pull_request:
        branches: [master]

jobs:
    build:
        name: Build on PR to Master on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [12.x]
                os: [ubuntu-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Environment Variable
              run: |
                  echo "PULL_REQUEST_NUMBER=$(echo ${{github.event.pull_request.number}} | cut -c 1-6)" >> $GITHUB_ENV
                  echo "PULL_REQUEST_TITLE=$(echo ${{github.event.pull_request.title}} | cut -c 1-6)" >> $GITHUB_ENV
                  echo "PULL_REQUEST_HTML_URL=$(echo ${{github.event.pull_request.html_url}} | cut -c 1-6)" >> $GITHUB_ENV

            - name: Test Read Environment Variable
              run: |
                  echo $PULL_REQUEST_NUMBER
                  echo $PULL_REQUEST_TITLE
                  echo $PULL_REQUEST_HTML_URL

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Loading Cached Dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: NPM install, build and test
              run: |
                  npm ci
                  npm run build --if-present
                  npm run test:coverage

            - name: Report if build success
              if: ${{ success() }}
              uses: satak/webrequest-action@master
              with:
                  url: https://postman-echo.com/post
                  method: POST
                  headers: '{"Content-Type": "application/json"}'
                  payload: '{ "status": "success"}'

            - name: Report if build failed
              if: ${{ failure() }}
              uses: satak/webrequest-action@master
              with:
                  url: https://postman-echo.com/post
                  method: POST
                  headers: '{"Content-Type": "application/json"}'
                  payload: '{ "status": "failed"}'
